/**
 * Menu + permission matrix tree (same idea as DWP pageConfig).
 * Keys must match backend `app_nav_permissions.APP_PERMISSION_SEEDS`.
 *
 * Pages: always a .view / .edit pair. Action rows: `showInNav: false`.
 */
export type PagePermissions = { view: string; edit: string }

export type PageConfig = {
  id: string
  name: string
  basePath?: string
  parent?: string
  module: string
  permissions: PagePermissions
  showInNav?: boolean
}

export const appPages: PageConfig[] = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    basePath: '/',
    module: 'dashboard',
    permissions: { view: 'dashboard.view', edit: 'dashboard.edit' },
    showInNav: true,
  },
  {
    id: 'customers-root',
    name: 'Customers',
    basePath: '/customers',
    module: 'customers',
    permissions: { view: 'customers.view', edit: 'customers.edit' },
    showInNav: true,
  },
  {
    id: 'estimates-root',
    name: 'Estimates',
    basePath: '/estimates',
    module: 'estimates',
    permissions: { view: 'estimates.view', edit: 'estimates.edit' },
    showInNav: true,
  },
  {
    id: 'orders-root',
    name: 'Orders',
    basePath: '/orders',
    module: 'orders',
    permissions: { view: 'orders.view', edit: 'orders.edit' },
    showInNav: true,
  },
  {
    id: 'lookups-root',
    name: 'Lookups',
    basePath: '/lookups',
    module: 'lookups',
    permissions: { view: 'lookups.view', edit: 'lookups.edit' },
    showInNav: true,
  },
  {
    id: 'lookups-blinds-types',
    name: 'Blinds types',
    basePath: '/lookups/blinds-types',
    parent: 'lookups-root',
    module: 'lookups',
    permissions: { view: 'lookups.view', edit: 'lookups.edit' },
    showInNav: true,
  },
  {
    id: 'lookups-order-statuses',
    name: 'Order statuses',
    basePath: '/lookups/order-statuses',
    parent: 'lookups-root',
    module: 'lookups',
    permissions: { view: 'lookups.view', edit: 'lookups.edit' },
    showInNav: true,
  },
  {
    id: 'lookups-blinds-product-categories',
    name: 'Product categories',
    basePath: '/lookups/blinds-product-categories',
    parent: 'lookups-root',
    module: 'lookups',
    permissions: { view: 'lookups.view', edit: 'lookups.edit' },
    showInNav: true,
  },
  {
    id: 'lookups-blinds-lifting-options',
    name: 'Lifting system options',
    basePath: '/lookups/blinds-extra-options/lifting_system',
    parent: 'lookups-root',
    module: 'lookups',
    permissions: { view: 'lookups.view', edit: 'lookups.edit' },
    showInNav: true,
  },
  {
    id: 'lookups-blinds-cassette-options',
    name: 'Cassette type options',
    basePath: '/lookups/blinds-extra-options/cassette_type',
    parent: 'lookups-root',
    module: 'lookups',
    permissions: { view: 'lookups.view', edit: 'lookups.edit' },
    showInNav: true,
  },
  {
    id: 'companies-root',
    name: 'Companies',
    basePath: '/companies',
    module: 'companies',
    permissions: { view: 'companies.view', edit: 'companies.edit' },
    showInNav: true,
  },
  {
    id: 'users-root',
    name: 'Users',
    basePath: '/users',
    module: 'users',
    permissions: { view: 'users.directory.view', edit: 'users.directory.edit' },
    showInNav: true,
  },
  {
    id: 'reports-root',
    name: 'Reports',
    basePath: '/reports',
    module: 'reports',
    permissions: { view: 'reports.access.view', edit: 'reports.access.edit' },
    showInNav: true,
  },
  {
    id: 'reports-overview',
    name: 'Overview',
    basePath: '/reports',
    parent: 'reports-root',
    module: 'reports',
    permissions: { view: 'reports.access.view', edit: 'reports.access.edit' },
    /** Same URL as Reports parent; hub content opens when you click the Reports row (no extra nav item). */
    showInNav: false,
  },
  {
    id: 'reports-ops',
    name: 'Operational',
    basePath: '/reports/ops',
    parent: 'reports-root',
    module: 'reports',
    permissions: { view: 'reports.ops.view', edit: 'reports.ops.edit' },
    showInNav: true,
  },
  {
    id: 'reports-ops-quarter',
    name: 'Quarterly summary',
    basePath: '/reports/ops/quarter',
    parent: 'reports-ops',
    module: 'reports',
    permissions: { view: 'reports.ops.quarter.view', edit: 'reports.ops.quarter.edit' },
    showInNav: true,
  },
  {
    id: 'reports-ops-quarter-detail',
    name: 'Detail view',
    basePath: '/reports/ops/quarter/detail',
    parent: 'reports-ops-quarter',
    module: 'reports',
    permissions: {
      view: 'reports.ops.quarter.detail.view',
      edit: 'reports.ops.quarter.detail.edit',
    },
    showInNav: true,
  },
  {
    id: 'reports-detail-action-edit',
    name: '… Button: Edit',
    parent: 'reports-ops-quarter-detail',
    module: 'reports',
    permissions: {
      view: 'reports.ops.quarter.detail.btn_edit.view',
      edit: 'reports.ops.quarter.detail.btn_edit.edit',
    },
    showInNav: false,
  },
  {
    id: 'reports-detail-action-delete',
    name: '… Button: Delete',
    parent: 'reports-ops-quarter-detail',
    module: 'reports',
    permissions: {
      view: 'reports.ops.quarter.detail.btn_delete.view',
      edit: 'reports.ops.quarter.detail.btn_delete.edit',
    },
    showInNav: false,
  },
  {
    id: 'reports-detail-action-print',
    name: '… Button: Print',
    parent: 'reports-ops-quarter-detail',
    module: 'reports',
    permissions: {
      view: 'reports.ops.quarter.detail.btn_print.view',
      edit: 'reports.ops.quarter.detail.btn_print.edit',
    },
    showInNav: false,
  },
  {
    id: 'settings-group',
    name: 'Settings',
    basePath: '/settings',
    module: 'settings',
    permissions: { view: 'settings.access.view', edit: 'settings.access.edit' },
    showInNav: true,
  },
  {
    id: 'permissions-group',
    name: 'Permissions',
    basePath: '/permissions',
    module: 'settings',
    permissions: { view: 'settings.access.view', edit: 'settings.access.edit' },
    showInNav: true,
  },
  {
    id: 'settings-roles',
    name: 'Roles',
    basePath: '/permissions/roles',
    parent: 'permissions-group',
    module: 'settings',
    permissions: { view: 'settings.roles.view', edit: 'settings.roles.edit' },
    showInNav: true,
  },
  {
    id: 'settings-role-matrix',
    name: 'Role permissions',
    basePath: '/permissions/role-matrix',
    parent: 'permissions-group',
    module: 'settings',
    permissions: { view: 'settings.role_matrix.view', edit: 'settings.role_matrix.edit' },
    showInNav: true,
  },
  {
    id: 'settings-user-roles',
    name: 'User roles',
    basePath: '/permissions/user-roles',
    parent: 'permissions-group',
    module: 'settings',
    permissions: { view: 'settings.user_roles.view', edit: 'settings.user_roles.edit' },
    showInNav: true,
  },
  {
    id: 'settings-user-permissions',
    name: 'User permissions',
    basePath: '/permissions/user-permissions',
    parent: 'permissions-group',
    module: 'settings',
    permissions: {
      view: 'settings.user_permissions.view',
      edit: 'settings.user_permissions.edit',
    },
    showInNav: true,
  },
  {
    id: 'settings-pending-applications',
    name: 'Pending applications',
    basePath: '/settings/pending-applications',
    parent: 'settings-group',
    module: 'settings',
    permissions: {
      view: 'settings.pending_applications.view',
      edit: 'settings.pending_applications.edit',
    },
    showInNav: true,
  },
  {
    id: 'settings-company-info',
    name: 'Company info',
    basePath: '/settings/company-info',
    parent: 'settings-group',
    module: 'settings',
    permissions: { view: 'companies.view', edit: 'companies.edit' },
    showInNav: true,
  },
  {
    id: 'settings-integrations',
    name: 'Integrations',
    basePath: '/settings/integrations',
    parent: 'settings-group',
    module: 'settings',
    permissions: { view: 'companies.view', edit: 'companies.edit' },
    showInNav: true,
  },
  {
    id: 'settings-blinds-line-matrices',
    name: 'Blinds line matrices',
    basePath: '/settings/blinds-line-matrices',
    parent: 'settings-group',
    module: 'settings',
    permissions: { view: 'settings.access.view', edit: 'settings.access.edit' },
    showInNav: true,
  },
  {
    id: 'account-profile',
    name: 'Profile',
    basePath: '/account',
    module: 'account',
    permissions: { view: 'account.profile.view', edit: 'account.profile.edit' },
    showInNav: false,
  },
  {
    id: 'account-password',
    name: 'Change password',
    basePath: '/account/password',
    module: 'account',
    permissions: { view: 'account.password.view', edit: 'account.password.edit' },
    showInNav: false,
  },
]
