"""Permission keys aligned with app menu / matrix (.view / .edit pairs)."""

# (key, display name, target_id module, sort_index)
APP_PERMISSION_SEEDS: list[tuple[str, str, str, int]] = [
    ("dashboard.view", "Dashboard — view", "dashboard", 10),
    ("dashboard.edit", "Dashboard — edit", "dashboard", 11),
    ("customers.view", "Customers — view", "customers", 12),
    ("customers.edit", "Customers — edit", "customers", 13),
    ("estimates.view", "Estimates — view", "estimates", 14),
    ("estimates.edit", "Estimates — edit", "estimates", 15),
    ("orders.view", "Orders — view", "orders", 16),
    ("orders.edit", "Orders — edit", "orders", 17),
    ("lookups.view", "Lookups — view", "lookups", 18),
    ("lookups.edit", "Lookups — edit", "lookups", 19),
    ("account.password.view", "Account password — view", "account", 20),
    ("account.password.edit", "Account password — edit", "account", 21),
    ("account.profile.view", "Account profile — view", "account", 22),
    ("account.profile.edit", "Account profile — edit", "account", 23),
    ("companies.view", "Companies — view", "companies", 24),
    ("companies.edit", "Companies — edit", "companies", 25),
    ("users.directory.view", "Users directory — view", "users", 26),
    ("users.directory.edit", "Users directory — edit", "users", 27),
    ("settings.access.view", "Settings menu — view", "settings", 30),
    ("settings.access.edit", "Settings menu — edit", "settings", 31),
    ("settings.roles.view", "Roles — view", "settings", 40),
    ("settings.roles.edit", "Roles — edit", "settings", 41),
    ("settings.role_matrix.view", "Role permissions — view", "settings", 50),
    ("settings.role_matrix.edit", "Role permissions — edit", "settings", 51),
    ("settings.user_roles.view", "User roles — view", "settings", 60),
    ("settings.user_roles.edit", "User roles — edit", "settings", 61),
    ("settings.user_permissions.view", "User permissions — view", "settings", 70),
    ("settings.user_permissions.edit", "User permissions — edit", "settings", 71),
    ("settings.pending_applications.view", "Pending applications — view", "settings", 72),
    ("settings.pending_applications.edit", "Pending applications — edit", "settings", 73),
    ("reports.access.view", "Reports — view", "reports", 80),
    ("reports.access.edit", "Reports — edit", "reports", 81),
    ("reports.ops.view", "Reports / Operational — view", "reports", 82),
    ("reports.ops.edit", "Reports / Operational — edit", "reports", 83),
    ("reports.ops.quarter.view", "Reports / Quarterly summary — view", "reports", 84),
    ("reports.ops.quarter.edit", "Reports / Quarterly summary — edit", "reports", 85),
    ("reports.ops.quarter.detail.view", "Reports / Detail screen — view", "reports", 86),
    ("reports.ops.quarter.detail.edit", "Reports / Detail screen — edit", "reports", 87),
    ("reports.ops.quarter.detail.btn_edit.view", "Reports / Detail — Edit button (visible)", "reports", 88),
    ("reports.ops.quarter.detail.btn_edit.edit", "Reports / Detail — Edit button (action)", "reports", 89),
    ("reports.ops.quarter.detail.btn_delete.view", "Reports / Detail — Delete button (visible)", "reports", 90),
    ("reports.ops.quarter.detail.btn_delete.edit", "Reports / Detail — Delete button (action)", "reports", 91),
    ("reports.ops.quarter.detail.btn_print.view", "Reports / Detail — Print button (visible)", "reports", 92),
    ("reports.ops.quarter.detail.btn_print.edit", "Reports / Detail — Print button (action)", "reports", 93),
]

# Minimum menu permissions granted to the default `user` role
DEFAULT_USER_ROLE_PERMISSION_KEYS: tuple[str, ...] = (
    "dashboard.view",
    "dashboard.edit",
    "customers.view",
    "customers.edit",
    "estimates.view",
    "estimates.edit",
    "orders.view",
    "orders.edit",
    "lookups.view",
    "lookups.edit",
    "account.password.view",
    "account.password.edit",
    "account.profile.view",
    "account.profile.edit",
    "companies.view",
    "companies.edit",
)
