"""Permission keys aligned with app menu / matrix (.view / .edit pairs)."""

# (key, display name, target_id module, sort_index)
APP_PERMISSION_SEEDS: list[tuple[str, str, str, int]] = [
    ("dashboard.view", "Dashboard — view", "dashboard", 10),
    ("dashboard.edit", "Dashboard — edit", "dashboard", 11),
    ("schedule.view", "Schedule — view", "schedule", 11_000),
    ("schedule.edit", "Schedule — edit", "schedule", 11_001),
    ("customers.view", "Customers — view", "customers", 12),
    ("customers.edit", "Customers — edit", "customers", 13),
    ("estimates.view", "Estimates — view", "estimates", 14),
    ("estimates.edit", "Estimates — edit", "estimates", 15),
    ("orders.view", "Orders — view", "orders", 16),
    ("orders.edit", "Orders — edit", "orders", 17),
    ("lookups.view", "Lookups — view", "lookups", 18),
    ("lookups.edit", "Lookups — edit", "lookups", 19),
    ("lookups.blinds_types.view", "Lookups / Blinds types — view", "lookups", 124),
    ("lookups.blinds_types.edit", "Lookups / Blinds types — edit", "lookups", 125),
    ("lookups.order_statuses.view", "Lookups / Order statuses — view", "lookups", 126),
    ("lookups.order_statuses.edit", "Lookups / Order statuses — edit", "lookups", 127),
    ("lookups.estimate_statuses.view", "Lookups / Estimate statuses — view", "lookups", 128),
    ("lookups.estimate_statuses.edit", "Lookups / Estimate statuses — edit", "lookups", 129),
    ("lookups.product_categories.view", "Lookups / Product categories — view", "lookups", 130),
    ("lookups.product_categories.edit", "Lookups / Product categories — edit", "lookups", 131),
    ("account.password.view", "Account password — view", "account", 20),
    ("account.password.edit", "Account password — edit", "account", 21),
    ("account.profile.view", "Account profile — view", "account", 22),
    ("account.profile.edit", "Account profile — edit", "account", 23),
    ("companies.view", "Companies — view", "companies", 24),
    ("companies.edit", "Companies — edit", "companies", 25),
    ("users.directory.view", "Users directory — view", "users", 26),
    ("users.directory.edit", "Users directory — edit", "users", 27),
    ("settings.access.view", "Settings menu — view", "settings", 30),
    ("settings.access.edit", "Settings menu — edit", "settings", 31),
    ("settings.roles.view", "Roles — view", "settings", 40),
    ("settings.roles.edit", "Roles — edit", "settings", 41),
    ("settings.role_matrix.view", "Role permissions — view", "settings", 50),
    ("settings.role_matrix.edit", "Role permissions — edit", "settings", 51),
    ("settings.user_roles.view", "User roles — view", "settings", 60),
    ("settings.user_roles.edit", "User roles — edit", "settings", 61),
    ("settings.user_permissions.view", "User permissions — view", "settings", 70),
    ("settings.user_permissions.edit", "User permissions — edit", "settings", 71),
    ("settings.estimate_status_matrix.view", "Estimate statuses — view", "settings", 74),
    ("settings.estimate_status_matrix.edit", "Estimate statuses — edit", "settings", 75),
    ("settings.order_status_matrix.view", "Order statuses — view", "settings", 76),
    ("settings.order_status_matrix.edit", "Order statuses — edit", "settings", 77),
    ("settings.pending_applications.view", "Pending applications — view", "settings", 78),
    ("settings.pending_applications.edit", "Pending applications — edit", "settings", 79),
    ("settings.company_info.view", "Settings — Company info — view", "settings", 80),
    ("settings.company_info.edit", "Settings — Company info — edit", "settings", 81),
    ("settings.integrations.view", "Settings — Integrations — view", "settings", 82),
    ("settings.integrations.edit", "Settings — Integrations — edit", "settings", 83),
    ("settings.blinds_line_matrices.view", "Settings — Blinds line matrices — view", "settings", 84),
    ("settings.blinds_line_matrices.edit", "Settings — Blinds line matrices — edit", "settings", 85),
    ("settings.contract_invoice.view", "Settings — Contract / Invoice — view", "settings", 88),
    ("settings.contract_invoice.edit", "Settings — Contract / Invoice — edit", "settings", 89),
    ("permissions.access.view", "Permissions hub — view", "permissions", 86),
    ("permissions.access.edit", "Permissions hub — edit", "permissions", 87),
    ("reports.access.view", "Reports — view", "reports", 110),
    ("reports.access.edit", "Reports — edit", "reports", 111),
    ("reports.ops.view", "Reports / Operational — view", "reports", 112),
    ("reports.ops.edit", "Reports / Operational — edit", "reports", 113),
    ("reports.ops.quarter.view", "Reports / Quarterly summary — view", "reports", 114),
    ("reports.ops.quarter.edit", "Reports / Quarterly summary — edit", "reports", 115),
    ("reports.ops.quarter.detail.view", "Reports / Detail screen — view", "reports", 116),
    ("reports.ops.quarter.detail.edit", "Reports / Detail screen — edit", "reports", 117),
    ("reports.ops.quarter.detail.btn_edit.view", "Reports / Detail — Edit button (visible)", "reports", 118),
    ("reports.ops.quarter.detail.btn_edit.edit", "Reports / Detail — Edit button (action)", "reports", 119),
    ("reports.ops.quarter.detail.btn_delete.view", "Reports / Detail — Delete button (visible)", "reports", 120),
    ("reports.ops.quarter.detail.btn_delete.edit", "Reports / Detail — Delete button (action)", "reports", 121),
    ("reports.ops.quarter.detail.btn_print.view", "Reports / Detail — Print button (visible)", "reports", 122),
    ("reports.ops.quarter.detail.btn_print.edit", "Reports / Detail — Print button (action)", "reports", 123),
]

# Minimum menu permissions granted to the default `user` role
DEFAULT_USER_ROLE_PERMISSION_KEYS: tuple[str, ...] = (
    "dashboard.view",
    "dashboard.edit",
    "schedule.view",
    "schedule.edit",
    "customers.view",
    "customers.edit",
    "estimates.view",
    "estimates.edit",
    "orders.view",
    "orders.edit",
    "lookups.view",
    "lookups.edit",
    "lookups.blinds_types.view",
    "lookups.blinds_types.edit",
    "lookups.order_statuses.view",
    "lookups.order_statuses.edit",
    "lookups.estimate_statuses.view",
    "lookups.estimate_statuses.edit",
    "lookups.product_categories.view",
    "lookups.product_categories.edit",
    "account.password.view",
    "account.password.edit",
    "account.profile.view",
    "account.profile.edit",
    "companies.view",
    "companies.edit",
)
